### PR TITLE
Enables Kubernetes image updates for existing environment repos.

### PR DESCRIPTION
**Pull request by cmfcruz**
Change-type: minor

### CODE REVIEW

**Comment by ab77** [comment]
@klutchell do we want to do this globally or override in each environment repo, what do you think? cc @cmfcruz

**Comment by klutchell** [comment]
> @klutchell do we want to do this globally or override in each environment repo, what do you think? cc @cmfcruz

There is a match [here](https://github.com/product-os/product-os-keyframe), but it's been archived.

Are we going to want different kubernetes automerge y/n settings for each repo? If so, might be worth enabling at the repo level instead?

**Comment by ab77** [comment]
> > @klutchell do we want to do this globally or override in each environment repo, what do you think? cc @cmfcruz
> 
> There is a match [here](https://github.com/product-os/product-os-keyframe), but it's been archived.
> 
> Are we going to want different kubernetes automerge y/n settings for each repo? If so, might be worth enabling at the repo level instead?

My vote is to set these at repo level, since they are closer to the truth there.

**Comment by cmfcruz** [comment]
We'll add Kubernetes-specific configs at the repo level instead.

**Pull request closed without merging**
